import Image from "next/image"
import Link from "next/link"
import Script from "next/script"
import Head from "next/head"

import Layout from "../components/Layout"

const Index = () => {
  return (
    <Layout>
        <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        </Head>
      <h1>Welcome Joffrey to Next js App</h1>
      <div>
      <Image
        id="joffrey"
        src="/images/profile.jpg"
        alt="Joffrey profile"
        height={150}
        width={150}
        />
        <Link href="/about"> about page</Link>
        </div>
    </Layout>
  )
}

export default Index
